version: '3'

services:

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  game-of-three:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env.docker
    command: sh init.sh

volumes:
  mongodb_data:
